# Generated by Django 3.2.5 on 2021-07-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_name', models.CharField(max_length=30)),
                ('Patient_address', models.CharField(max_length=30)),
                ('Phone_No', models.IntegerField()),
            ],
        ),
    ]
